name: pyscenic_env
channels:
  - defaults
dependencies:
  - python=3.6.13
  - aiohttp=3.8.6
  - aiosignal=1.2.0
  - anndata=0.7.8
  - anyio=3.6.2
  - arboreto=0.1.6
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-generator=1.10
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=22.2.0
  - Babel=2.11.0
  - backcall=0.2.0
  - bleach=4.1.0
  - bokeh=2.3.3
  - boltons=23.1.1
  - cached-property=1.5.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.0.12
  - click=8.0.4
  - cloudpickle=2.2.1
  - colorcet=3.0.1
  - contextvars=2.4
  - ctxcore=0.1.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask=2021.3.0
  - dataclasses=0.8
  - datashader=0.13.0
  - datashape=0.5.2
  - decorator=4.4.2
  - defusedxml=0.7.1
  - dill=0.3.4
  - distributed=2021.3.0
  - entrypoints=0.4
  - frozendict=2.4.6
  - frozenlist=1.2.0
  - fsspec=2022.1.0
  - get_version=2.1
  - h5py=2.10.0
  - HeapDict=1.0.1
  - holoviews=1.14.9
  - idna=3.10
  - idna-ssl=1.1.0
  - imageio=2.15.0
  - immutables=0.19
  - importlib-metadata=4.8.3
  - importlib-resources=5.4.0
  - interlap=0.2.7
  - ipykernel=5.5.6
  - ipython=7.16.3
  - ipython-genutils=0.2.0
  - jedi=0.17.2
  - Jinja2=3.0.3
  - joblib=1.1.1
  - json5=0.9.16
  - jsonschema=3.2.0
  - jupyter-client=7.1.2
  - jupyter-core=4.9.2
  - jupyter-server=1.13.1
  - jupyterlab=3.2.9
  - jupyterlab-pygments=0.1.2
  - jupyterlab-server=2.10.3
  - kiwisolver=1.3.1
  - legacy-api-wrap=1.2
  - llvmlite=0.36.0
  - locket=1.0.0
  - loompy=3.0.8
  - louvain=0.7.0
  - Markdown=3.3.7
  - MarkupSafe=2.0.1
  - matplotlib=3.3.4
  - mistune=0.8.4
  - mkl-fft=1.3.0
  - mkl-random=1.1.1
  - mkl-service=2.3.0
  - mock=4.0.3
  - msgpack=1.0.5
  - MulticoreTSNE=0.1
  - multidict=5.2.0
  - multipledispatch=1.0.0
  - multiprocessing-on-dill=3.5.0a4
  - natsort=8.2.0
  - nbclassic=0.3.5
  - nbclient=0.5.9
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.6.0
  - networkx=2.5.1
  - notebook=6.4.10
  - numba=0.53.1
  - numexpr=2.7.3
  - numpy=1.19.5
  - numpy-groupies=0.9.22
  - olefile=0.46
  - packaging=21.3
  - pandas=1.1.5
  - pandocfilters=1.5.1
  - panel=0.12.1
  - param=1.13.0
  - parso=0.7.1
  - partd=1.2.0
  - patsy=0.5.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - Pillow=8.4.0
  - pip=21.2.2
  - prometheus-client=0.17.1
  - prompt-toolkit=3.0.36
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pyarrow=0.16.0
  - pycparser=2.21
  - pyct=0.4.8
  - Pygments=2.14.0
  - pynndescent=0.5.13
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pyscenic=0.11.2
  - python-dateutil=2.8.2
  - python-igraph=0.9.6
  - pytz=2021.3
  - pyviz-comms=2.2.1
  - PyWavelets=1.1.1
  - PyYAML=6.0.1
  - pyzmq=25.1.2
  - requests=2.27.1
  - scanpy=1.7.2
  - scikit-image=0.17.2
  - scikit-learn=0.24.2
  - scipy=1.5.4
  - seaborn=0.11.2
  - Send2Trash=1.8.3
  - setuptools=59.6.0
  - sinfo=0.3.4
  - six=1.16.0
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - statsmodels=0.12.2
  - stdlib-list=0.8.0
  - tables=3.6.1
  - tblib=1.7.0
  - terminado=0.12.1
  - testpath=0.6.0
  - texttable=1.7.0
  - threadpoolctl=3.1.0
  - tifffile=2020.9.3
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=4.3.3
  - typing_extensions=4.1.1
  - umap-learn=0.5.1
  - urllib3=1.26.20
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.3.1
  - wheel=0.37.1
  - xarray=0.16.2
  - xlrd=1.2.0
  - yarl=1.7.2
  - zict=2.1.0
  - zipp=3.6.0
